### PR TITLE
Fixing the broken tests

### PR DESCRIPTION
**Pull request by Omkar20895**
- There is one test that is still breaking for the sub routine test_granule_subset(...).
- I have raise a ticket for the same in podaac forum [here](https://podaac.jpl.nasa.gov/forum/viewtopic.php?f=53&t=563).

@lewismc please take a look at this. Thanks.

### CODE REVIEW

**Comment by lewismc** [comment]
```
======================================================================

ERROR: test_dataset_search (podaac.tests.l2ss_tests.test_podaac)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/nasa/podaacpy/podaac/tests/l2ss_tests.py", line 41, in test_dataset_search

    assert dataset_json['response']['docs'][0][

IndexError: list index out of range

-------------------- >> begin captured logging << --------------------

requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): podaac-tools.jpl.nasa.gov

requests.packages.urllib3.connectionpool: DEBUG: http://podaac-tools.jpl.nasa.gov:80 "GET /l2ss-services/l2ss/dataset/search?datasetId=PODAAC-ASOP2-25X01&variable=Surface%20Winds&sensor=Advanced%20Scatterometer&provider=KNMI&startTime=2016-12-4T22:39:52Z&startIndex=0&itemsPerPage=7 HTTP/1.1" 302 437

requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): podaac-tools.jpl.nasa.gov

requests.packages.urllib3.connectionpool: DEBUG: https://podaac-tools.jpl.nasa.gov:443 "GET /l2ss-services/l2ss/dataset/search?datasetId=PODAAC-ASOP2-25X01&variable=Surface%2520Winds&sensor=Advanced%2520Scatterometer&provider=KNMI&startTime=2016-12-4T22:39:52Z&startIndex=0&itemsPerPage=7 HTTP/1.1" 200 1655

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_granule_download (podaac.tests.l2ss_tests.test_podaac)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/nasa/podaacpy/podaac/tests/l2ss_tests.py", line 134, in test_granule_download

    self.l2ss.granule_download(query_string=query)

  File "/home/travis/build/nasa/podaacpy/podaac/l2ss.py", line 306, in granule_download

    result = json.loads(data)

  File "/opt/python/3.5.2/lib/python3.5/json/__init__.py", line 319, in loads

    return _default_decoder.decode(s)

  File "/opt/python/3.5.2/lib/python3.5/json/decoder.py", line 339, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/opt/python/3.5.2/lib/python3.5/json/decoder.py", line 357, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================

ERROR: test_granule_search (podaac.tests.l2ss_tests.test_podaac)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/nasa/podaacpy/podaac/tests/l2ss_tests.py", line 66, in test_granule_search

    items_per_page=items_per_page, start_index=start_index, name=name, sort=sort)

  File "/home/travis/build/nasa/podaacpy/podaac/l2ss.py", line 175, in granule_search

    granules.raise_for_status()

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests-2.13.0-py3.5.egg/requests/models.py", line 909, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://podaac-tools.jpl.nasa.gov/l2ss-services/l2ss/granule/search?datasetId=PODAAC-ASOP2-25X01&bbox=-180,-90,180,90&startTime=2016-07-16T04:18:00Z&endTime=2016-07-16T05:56:56Z&startIndex=0&itemsPerPage=7&name=ascat_20160716_041800_metopa_50541_eps_o_250_2401_ovw.l2.nc&sort=Granule-Name%2520asc

-------------------- >> begin captured stdout << ---------------------

404 Client Error: Not Found for url: https://podaac-tools.jpl.nasa.gov/l2ss-services/l2ss/granule/search?datasetId=PODAAC-ASOP2-25X01&bbox=-180,-90,180,90&startTime=2016-07-16T04:18:00Z&endTime=2016-07-16T05:56:56Z&startIndex=0&itemsPerPage=7&name=ascat_20160716_041800_metopa_50541_eps_o_250_2401_ovw.l2.nc&sort=Granule-Name%2520asc

--------------------- >> end captured stdout << ----------------------

-------------------- >> begin captured logging << --------------------

requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): podaac-tools.jpl.nasa.gov

requests.packages.urllib3.connectionpool: DEBUG: http://podaac-tools.jpl.nasa.gov:80 "GET /l2ss-services/l2ss/granule/search?datasetId=PODAAC-ASOP2-25X01&bbox=-180,-90,180,90&startTime=2016-07-16T04:18:00Z&endTime=2016-07-16T05:56:56Z&startIndex=0&itemsPerPage=7&name=ascat_20160716_041800_metopa_50541_eps_o_250_2401_ovw.l2.nc&sort=Granule-Name%20asc HTTP/1.1" 302 508

requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): podaac-tools.jpl.nasa.gov

requests.packages.urllib3.connectionpool: DEBUG: https://podaac-tools.jpl.nasa.gov:443 "GET /l2ss-services/l2ss/granule/search?datasetId=PODAAC-ASOP2-25X01&bbox=-180,-90,180,90&startTime=2016-07-16T04:18:00Z&endTime=2016-07-16T05:56:56Z&startIndex=0&itemsPerPage=7&name=ascat_20160716_041800_metopa_50541_eps_o_250_2401_ovw.l2.nc&sort=Granule-Name%2520asc HTTP/1.1" 404 21

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_check_local_file (podaac.tests.mcc_test.testMCC)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/nasa/podaacpy/podaac/tests/mcc_test.py", line 43, in test_check_local_file

    data = self.mcc.check_local_file(1.1, 'L2P', path)

  File "/home/travis/build/nasa/podaacpy/podaac/mcc.py", line 95, in check_local_file

    result.raise_for_status()

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests-2.13.0-py3.5.egg/requests/models.py", line 909, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: https://podaac-uat.jpl.nasa.gov/mcc/check

-------------------- >> begin captured stdout << ---------------------

400 Client Error: BAD REQUEST for url: https://podaac-uat.jpl.nasa.gov/mcc/check

--------------------- >> end captured stdout << ----------------------

-------------------- >> begin captured logging << --------------------

requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): podaac-uat.jpl.nasa.gov

requests.packages.urllib3.connectionpool: DEBUG: http://podaac-uat.jpl.nasa.gov:80 "POST /mcc/check HTTP/1.1" 302 225

requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): podaac-uat.jpl.nasa.gov

requests.packages.urllib3.connectionpool: DEBUG: https://podaac-uat.jpl.nasa.gov:443 "GET /mcc/check HTTP/1.1" 400 1042

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_granule_subset (podaac.tests.podaac_test.test_podaac)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/nasa/podaacpy/podaac/tests/podaac_test.py", line 162, in test_granule_subset

    self.podaac.granule_subset(input_file_path=path1, path=path2)

  File "/home/travis/build/nasa/podaacpy/podaac/podaac.py", line 511, in granule_subset

    result = json.loads(data)

  File "/opt/python/3.5.2/lib/python3.5/json/__init__.py", line 319, in loads

    return _default_decoder.decode(s)

  File "/opt/python/3.5.2/lib/python3.5/json/decoder.py", line 339, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/opt/python/3.5.2/lib/python3.5/json/decoder.py", line 357, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Omkar20895** [comment]
WTH! The test cases passed in my local machine. I will take a look into this again first thing in the morning. Thanks.

**Comment by Omkar20895** [comment]
Okay so there are three testcases that are failing, two of them include downloading a granule and I raised an issue for it in podaac forum. The third one is test_check_local_file is failing with an error STATUS 400 Bad Request. 

The response is following : 
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>There was a problem with your request.</title>

    <!-- Bootstrap -->
    <link href="./static/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h1>There was a problem with your request.</h1>
          <p class="lead"></p>
<p>You must specify at least one test.</p>        </div>
      </div>
    </div>
  </body>
</html>
```

I am unable to find out the reason for this, @lewismc can you please help me out with this? Thanks.

**Comment by Omkar20895** [comment]
@lewismc please ignore the above mentioned issue. Apparently, PODAAC has been upgraded from HTTP server to HTTPS server and that is the reason our code broke. I will clean up this PR or send a new one as soon as I have a solution at the podaac forum thread. Please take a look at the thread over there. Thanks.

**Comment by lewismc** [comment]
@Omkar20895 can you post the thread here please?

**Comment by Omkar20895** [comment]
@lewismc Please find the thread [here](https://podaac.jpl.nasa.gov/forum/viewtopic.php?f=53&t=563). Thanks.

**Comment by Omkar20895** [comment]
I will send a new PR with resolved testcases. Closing this one. Thanks.

**Pull request closed without merging**
