### PR TITLE
Updating dataset_variable to support L3 and L4 datasets

### PR DESCRIPTION
**Pull request by Omkar20895**
This PR is only an update to the dataset_variable function and does not include the complete solution to #128.

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @Omkar20895 this doesn't look too bad. See the following tests... I am experiencing issues with retrieval of variables from all Level3 collections I've tried so far.

This is Level1B [SeaWinds on QuikSCAT Level 1B Time-Ordered Earth-Located Sigma0 Version 2](https://podaac.jpl.nasa.gov/dataset/QSCAT_LEVEL_1B_V2)
```
>>> print(p.dataset_variables('PODAAC-QSXXX-L1B02'))
['orbit_time', 'frame_inst_status', 'frame_err_status', 'frame_qual_flag', 'num_pulses', 'sc_lat', 'sc_lon', 'sc_alt', 'x_pos', 'y_pos', 'z_pos', 'x_vel', 'y_vel', 'z_vel', 'roll', 'pitch', 'yaw', 'bandwidth_ratio', 'x_cal_A', 'x_cal_B', 'cell_lat', 'cell_lon', 'sigma0_mode_flag', 'sigma0_qual_flag', 'cell_sigma0', 'frequency_shift', 'cell_azimuth', 'cell_incidence', 'antenna_azimuth', 'cell_snr', 'cell_kpc_a', 'qscat_app_tb', 'slice_qual_flag', 'slice_lat', 'slice_lon', 'slice_sigma0', 'x_factor', 'slice_azimuth', 'slice_incidence', 'slice_snr', 'slice_kpc_a', 'vdata_frame_time_vdf_frame_time']
```

This is Level2 [OSTM GPS based orbit and SSHA OGDR](https://podaac.jpl.nasa.gov/dataset/OSTM_L2_OST_OGDR_GPS)
```
>>> print(p.dataset_variables('PODAAC-J2ODR-GPS00'))
['time', 'lat', 'lon', 'surface_type', 'alt_echo_type', 'rad_surf_type', 'alt_quality_flag', 'rad_quality_flag', 'geophysical_quality_flag', 'ecmwf_meteo_map_avail', 'rain_flag', 'rad_rain_flag', 'ice_flag', 'rad_sea_ice_flag', 'alt', 'range_ku', 'range_ku_mle3', 'model_dry_tropo_corr', 'rad_wet_tropo_corr', 'iono_corr_alt_ku', 'iono_corr_alt_ku_mle3', 'sea_state_bias_ku', 'sea_state_bias_ku_mle3', 'swh_ku', 'swh_ku_mle3', 'sig0_ku', 'sig0_ku_mle3', 'mean_sea_surface', 'mean_topography', 'bathymetry', 'inv_bar_corr', 'hf_fluctuations_corr', 'ocean_tide_sol1', 'solid_earth_tide', 'pole_tide', 'wind_speed_alt', 'wind_speed_alt_mle3', 'rad_water_vapor', 'rad_liquid_water', 'ssha', 'ssha_mle3', 'gps_alt', 'gps_ssha']
```

Level3 [SeaWinds on ADEOS-II Level 3 Sigma-0 Polar-Stereographic Browse Images of Antarctica ](https://podaac.jpl.nasa.gov/dataset/SEAWINDS_BYU_L3_OW_SIGMA0_ANTARCTICA_POLAR-STEREOGRAPHIC_BROWSE_IMAGES)
```
>>> print(p.dataset_variables('PODAAC-SEABY-ANBIM'))
404 Client Error: Not Found for url: https://podaac.jpl.nasa.gov/ws/search/granule/?datasetId=PODAAC-SEABY-ANBIM&sortBy=timeAsc&itemsPerPage=7&format=atom&pretty=True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/podaacpy-2.2.1-py3.6.egg/podaac/podaac.py", line 220, in dataset_variables
    dataset = self.granule_search(dataset_id = dataset_id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/podaacpy-2.2.1-py3.6.egg/podaac/podaac.py", line 423, in granule_search
    granules.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://podaac.jpl.nasa.gov/ws/search/granule/?datasetId=PODAAC-SEABY-ANBIM&sortBy=timeAsc&itemsPerPage=7&format=atom&pretty=True
```

Level3 [SEASAT SCATTEROMETER DEALIASED OCEAN WIND VECTORS](https://podaac.jpl.nasa.gov/dataset/UCLA_DEALIASED_SASS_L3)
```
>>> print(p.dataset_variables('PODAAC-SASSX-L3UCD'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/podaacpy-2.2.1-py3.6.egg/podaac/podaac.py", line 229, in dataset_variables
    dataset_ddx_response = requests.get(dataset_url, headers=HEADERS)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 294, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 354, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
```

Level3 [SeaWinds on QuikSCAT Level 3 Sigma-0 Polar-Stereographic Browse Images of Antarctica](https://podaac.jpl.nasa.gov/dataset/QSCAT_BYU_L3_OW_SIGMA0_ANTARCTICA_POLAR-STEREOGRAPHIC_BROWSE_IMAGES)
```
>>> print(p.dataset_variables('PODAAC-QSBYU-ANBIM'))
404 Client Error: Not Found for url: https://podaac.jpl.nasa.gov/ws/search/granule/?datasetId=PODAAC-QSBYU-ANBIM&sortBy=timeAsc&itemsPerPage=7&format=atom&pretty=True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/podaacpy-2.2.1-py3.6.egg/podaac/podaac.py", line 220, in dataset_variables
    dataset = self.granule_search(dataset_id = dataset_id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/podaacpy-2.2.1-py3.6.egg/podaac/podaac.py", line 423, in granule_search
    granules.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://podaac.jpl.nasa.gov/ws/search/granule/?datasetId=PODAAC-QSBYU-ANBIM&sortBy=timeAsc&itemsPerPage=7&format=atom&pretty=True
```

Level3 [GRACE MONTHLY OCEAN MASS EOF GRIDS GIF CSR RELEASE 5.0](https://podaac.jpl.nasa.gov/dataset/TELLUS_OCEANEOF_GIF_CSR_RL05)
```
>>> print(p.dataset_variables('PODAAC-TEOCN-EGC05'))
404 Client Error: Not Found for url: https://podaac.jpl.nasa.gov/ws/search/granule/?datasetId=PODAAC-TEOCN-EGC05&sortBy=timeAsc&itemsPerPage=7&format=atom&pretty=True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/podaacpy-2.2.1-py3.6.egg/podaac/podaac.py", line 220, in dataset_variables
    dataset = self.granule_search(dataset_id = dataset_id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/podaacpy-2.2.1-py3.6.egg/podaac/podaac.py", line 423, in granule_search
    granules.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://podaac.jpl.nasa.gov/ws/search/granule/?datasetId=PODAAC-TEOCN-EGC05&sortBy=timeAsc&itemsPerPage=7&format=atom&pretty=True
```

Level4 Blended [Cross-Calibrated Multi-Platform Ocean Surface Wind Vector L3.5A Pentad First-Look Analyses](https://podaac.jpl.nasa.gov/dataset/CCMP_MEASURES_ATLAS_L4_OW_L3_5A_5DAY_WIND_VECTORS_FLK)
```
>>> print(p.dataset_variables('PODAAC-CCF35-01AD5'))
['lon', 'lat', 'time', 'uwnd', 'vwnd', 'wspd', 'upstr', 'vpstr', 'nobs']
```

Level4 Blended [GHRSST Level 4 DMI_OI North Sea and Baltic Sea Regional Foundation Sea Surface Temperature Analysis](https://podaac.jpl.nasa.gov/dataset/DMI-L4UHfnd-NSEABALTIC-DMI_OI)
```
>>> print(p.dataset_variables('PODAAC-GHBDM-4FD01'))
['lon', 'lat', 'time', 'analysed_sst', 'analysis_error', 'mask']
```

**Comment by lewismc** [comment]
We should also add additional test scenario's for the dataset_variables function. Right now we only have a primitive test which asserts an error hasbeen raised. Please add the above scenario's as tests so that we have coverage of L1 through L4 dataset_variables tests.

**Comment by lewismc** [comment]
Also, we should edit the function description
```
        :param dataset_id: dataset persistent ID. dataset_id or short_name \
                is required for this metadata service.
        :type dataset_id: :mod:`string`

        :returns: a list of dataset variables for the dataset.
```
It is incorrect for us to state _**...dataset_id or short_name**_ when infact it is only dataset_id which is accepted.

**Comment by Omkar20895** [comment]
Hi @lewismc, thank you for your review. This was just a prototype function to get your review. I will test it today with the above-mentioned datasets and let you know. Thanks.

**Comment by lewismc** [comment]
@Omkar20895 any updates here mate? Did you get a chance to try out any L3 data with the new code?

**Comment by lewismc** [comment]
@Omkar20895 I'm going to take over work here to try and get this patch ready. Thanks for the work do far this is great.

**Comment by Omkar20895** [comment]
Hi @lewismc, apologies for the silence on this. I was on my spring break and got back yesterday. I have started working on it yesterday. 

The one thing I have observed with the above level 3 datasets is that they are not yet supported by the granule search web service that we have used to get dataset HTML link in the modified dataset_variables function in this PR. 

I tried using "dataset search" instead of "granule search" and I was able to get a text/html link but appending .ddx at the end of it did not work too. I have been trying to figure out other ways to get the OpeNDAP response for these datasets but unable to do so. Please let me know your thoughts on this and suggest some alternate way to do this.

**Comment by lewismc** [comment]
OK I think I've found a pretty ridiculous way to get this information.

**Step 1**
First for a given DatasetID execute a `dataset_search`
```
print(p.dataset_search(dataset_id='PODAAC-QSBYU-ANBIM'))
...
<?xml version="1.0" ?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/terms/" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:podaac="https://podaac.jpl.nasa.gov/opensearch/" xmlns:time="http://a9.com/-/opensearch/extensions/time/1.0/">
	<title>PO.DAAC Dataset Search Results</title>
	<updated>2019-03-09T16:27:56.805089Z</updated>
	<id>tag:podaac.jpl.nasa.gov,2019-03-09</id>
	<author>
		<name>PO.DAAC Dataset Search Service</name>
	</author>
	<link href="https://podaac.jpl.nasa.gov/ws/search/podaac-granule-osd.xml" rel="search" type="application/opensearchdescription+xml"/>
	<link href="https://podaac.jpl.nasa.gov/ws/search/dataset?startIndex=0&amp;itemsPerPage=7&amp;datasetId=PODAAC-QSBYU-ANBIM&amp;format=atom" rel="self" type="application/atom+xml"/>
	<link href="https://podaac.jpl.nasa.gov/ws/search/dataset?startIndex=0&amp;itemsPerPage=7&amp;datasetId=PODAAC-QSBYU-ANBIM&amp;format=atom" rel="first" type="application/atom+xml"/>
	<opensearch:totalResults>1</opensearch:totalResults>
	<opensearch:startIndex>0</opensearch:startIndex>
	<opensearch:itemsPerPage>7</opensearch:itemsPerPage>
	<entry>
		<title>SeaWinds on QuikSCAT Level 3 Sigma-0 Polar-Stereographic Browse Images of Antarctica</title>
		...
		<link href="https://podaac-tools.jpl.nasa.gov/drive/files/allData/quikscat/L3/byu_scp/sigma0browse/images/antarctic" rel="enclosure" title="HTTP URL" type="text/plain"/>
		<link href="https://podaac.jpl.nasa.gov/dataset/QSCAT_BYU_L3_OW_SIGMA0_ANTARCTICA_POLAR-STEREOGRAPHIC_BROWSE_IMAGES" rel="enclosure" title="Dataset Information" type="text/html"/>
...
```
As you can see from above. We _usually always_ get a HTTP Drive URL which in this case is https://podaac-tools.jpl.nasa.gov/drive/files/allData/quikscat/L3/byu_scp/sigma0browse/images/antarctic.

**Step 2**
Once authenticated with PO.DAAC Drive as one needs to do when creating a [Drive Object](https://github.com/nasa/podaacpy/blob/master/podaac/drive.py) we can then execute a GET request against the URL e.g. curl "https://podaac-tools.jpl.nasa.gov/drive/files/allData/quikscat/L3/byu_scp/sigma0browse/images/antarctic" this returns the HTML rendered page which we can mine (I am hoping the HTML is rendered using a standard HTML template) for the directory structure e.g. from HTML
```
...
    <td>
    	<a class="text-left" href="/drive/files/allData/quikscat/L3/byu_scp/sigma0browse/images">Parent Directory</a>
    </td>
    <td>-</td>
    <td>-</td>
</tr>
		        
		            <tr>
    <td>
    	
	    	<img src="/drive/static/images/icons/icon_dir.png" style="width:100%;">
	    
    </td>
    <td>
    	<a class="text-left" href="/drive/files/allData/quikscat/L3/byu_scp/sigma0browse/images/antarctic/1999">1999</a>
    </td>
    <td>2005-05-25 23:44:15</td>
    <td>-</td>
</tr>
...
```
As you can we can grab `/drive/files/allData/quikscat/L3/byu_scp/sigma0browse/images/antarctic/1999`, which when we execute a GET request against responds with the following page

https://podaac-tools.jpl.nasa.gov/drive/files/allData/quikscat/L3/byu_scp/sigma0browse/images/antarctic/1999

In this case, this page contains the **products** which are GIF's and not useful so we would return a response to the user indicating that. However in the case where we encountered say .nc4, .nc or .hdf files e.g. https://podaac-tools.jpl.nasa.gov/drive/files/allData/avhrr/L3/pathfinder_v5/monthly/day/04km/1985/01, then we would simply grab the location of the file in Drive e.g https://podaac-tools.jpl.nasa.gov/drive/files/allData/avhrr/L3/pathfinder_v5/monthly/day/04km/1985/01/198501.m04m3pfv50-msk1.hdf then replace the Drive service with Hyrax e.g. https://opendap.jpl.nasa.gov/opendap/allData/avhrr/L3/pathfinder_v5/monthly/day/04km/1985/01/198501.m04m3pfv50-msk1.hdf and then append `.ddx` e.g. https://opendap.jpl.nasa.gov/opendap/allData/avhrr/L3/pathfinder_v5/monthly/day/04km/1985/01/198501.m04m3pfv50-msk1.hdf.ddx. This results in a DDX file from which we can extract the variable names for more or less every dataset at PO.DAAC.

Does this make sense?

**Comment by Omkar20895** [comment]
@lewismc it makes sense but this is a really complex and funny workaround. The only concern I have is the presence of multiple dependency steps, the whole function would go haywire if there is a change of data format or something in any of the steps mentioned above. 

What I would suggest is fetching the list of datasets supported by [`dataset variables`](https://podaac.jpl.nasa.gov/ws/dataset/variables/index.html) endpoint provided by the web services API and checking if the input `datasetid` is present in that list and using the endpoint if it is present. Otherwise, enforce the above-mentioned workaround(by you). 

I don't know if this makes sense. Please let me know your thoughts on this. Thanks.

**Comment by lewismc** [comment]
+1 @Omkar20895 please go ahead with that logic, thanks.

**Comment by Omkar20895** [comment]
Sure @lewismc, I will add a commit as soon as I am done. Thanks.

**Comment by lewismc** [comment]
@Omkar20895 how is this going? I have been asked to implement another feature so I will work on that today. Hope all is going well with Uni :)

**Comment by Omkar20895** [comment]
Hi @lewismc, please feel free to go ahead, I am flustered with projects and assignment submissions right now as I am approaching the end of my semester. Thank you very much.

**Comment by ShubhamShaswat** [comment]
Hi,I was looking at the the proposed solution and I have a questions
In Step 1:
Why we are doing dataset_search?
Can't we just return that "Varibles Not Available",if we already knew that the OPeNDAP URL isn't available for the given datasetid (for Ex: PODAAC-QSBYU-ANBIM) when your done doing granule search.

And can  we do like this
Step 1: We do 'data_search()' and fetch the link title = "Granule Search" and if it's not there we will return "Granule Search not found".

Step 2: We will request the link from Step 1 and fetch the link  title = OPeNDAP URL and if its' not there we will return "OPeNDAP URL not  found".

Step 3: We will replace ".html" with ".ddx" and fetch the XML to get our variables.

**Comment by ShubhamShaswat** [comment]
Hi, I was looking at the propose solution and from my understanding I break down it in some smaller steps:
If I am wrong,Please correct me

Step 1: We do 'data_search()' and fetch the link title = "Granule Search" and if it's not there we go to the
and fetch the link title = "HTTP URL".

Step 2: if we have granule search we will request the link from Step 1 and fetch the link title = OPeNDAP URL and if it's not we will go to the HTTP URL.

Step 3: if its OPeNDAP URL then We will replace ".html" with ".ddx" and fetch the XML to get our variables.

Step 4: if its's HTTP URL then We will authenticate.

Step 5: Fetch the HTTP URL + syntax (for ex: https://podaac-tools.jpl.nasa.gov/drive/files/allData/quikscat/L3/byu_scp/sigma0browse/images/antarctic/1999).
Step 6: find any .nc, .hdf ,.nc4 files.

Step 7: If file is there ,We will add ".ddx" and fetch the XML to get our variables.

Step 8: if it's not there We will return 'Images Files Only".

**Comment by lewismc** [comment]
Yes @ShubhamShaswat that sounds excellent.

**Comment by ShubhamShaswat** [comment]
Thanks!! So,I'll start to write code on the basis of this steps and I'll let you know when it's done.So anything you would like to mention before I begin?

**Comment by lewismc** [comment]
> So anything you would like to mention before I begin?

No, thanks for taking this on.

**Comment by ShubhamShaswat** [comment]
Hi,I have some question regarding the PODAAC dataset id.
So,I have looking at the data you have tested for example "PODAAC-CCF35-01AD5" ,this datsetid return the when doing dataset search return XML response as 
`</content>
<link href="https://podaac.jpl.nasa.gov/ws/search/dataset?full=true&datasetId=PODAAC-TELND-PGTX1" rel="enclosure" title="PO.DAAC Metadata" type="application/atom+xml"/>
<link href="https://podaac.jpl.nasa.gov/ws/metadata/dataset?datasetId=PODAAC-TELND-PGTX1&format=iso" rel="enclosure" title="ISO-19115 Metadata" type="text/xml"/>
<link href="https://podaac.jpl.nasa.gov/ws/metadata/dataset?datasetId=PODAAC-TELND-PGTX1&format=gcmd" rel="enclosure" title="GCMD Metadata" type="text/xml"/>
<link href="https://podaac.jpl.nasa.gov/Podaac/thumbnails/TELLUS_PGR_TXT.jpg" rel="enclosure" title="Thumbnail" type="image/jpg"/>
<link href="ftp://podaac-ftp.jpl.nasa.gov/allData/tellus/L3/pgr" rel="enclosure" title="FTP URL" type="text/plain"/>
<link href="https://podaac-tools.jpl.nasa.gov/drive/files/allData/tellus/L3/pgr" rel="enclosure" title="HTTP URL" type="text/plain"/>
<link href="https://podaac.jpl.nasa.gov/dataset/TELLUS_PGR_TXT" rel="enclosure" title="Dataset Information" type="text/html"/>`
Here,HTTP URL have link https://podaac-tools.jpl.nasa.gov/drive/files/allData/tellus/L3/pgr

where as when we do granule search the XML response is this,

`<id>PODAAC-CCF35-01AD5:pentad_20111222_v11l35flk.nc</id>
<link href="https://podaac.jpl.nasa.gov/ws/search/granule?full=true&granuleName=pentad_20111222_v11l35flk.nc&datasetId=PODAAC-CCF35-01AD5" rel="enclosure" title="PO.DAAC Metadata" type="application/atom+xml"/>
<link href="https://podaac.jpl.nasa.gov/ws/metadata/granule?granuleName=pentad_20111222_v11l35flk.nc&datasetId=PODAAC-CCF35-01AD5&format=iso" rel="enclosure" title="ISO-19115 Metadata" type="text/xml"/>
<link href="https://podaac.jpl.nasa.gov/ws/metadata/granule?granuleName=pentad_20111222_v11l35flk.nc&datasetId=PODAAC-CCF35-01AD5&format=fgdc" rel="enclosure" title="FGDC Metadata" type="text/xml"/>
<link href="https://podaac-opendap.jpl.nasa.gov/opendap/allData/ccmp/L3.5a/pentad/flk/2011/12/pentad_20111222_v11l35flk.nc.gz.html" rel="enclosure" title="OPeNDAP URL" type="text/html"/>
<link href="ftp://podaac-ftp.jpl.nasa.gov/allData/ccmp/L3.5a/pentad/flk/2011/12/pentad_20111222_v11l35flk.nc.gz" rel="enclosure" title="FTP URL" type="application/x-netcdf"/>
<link href="https://podaac-tools.jpl.nasa.gov/drive/files/allData/ccmp/L3.5a/pentad/flk/2011/12/pentad_20111222_v11l35flk.nc.gz" rel="enclosure" title="HTTP URL" type="application/x-netcdf"/>`

here you can see the HTTP URL have link https://podaac-tools.jpl.nasa.gov/drive/files/allData/ccmp/L3.5a/pentad/flk/2011/12/pentad_20111222_v11l35flk.nc.gz

Also it have an OPeNDAP URL as well

**Pull request merged**
